#GirlsWhoML: Python Essentials

Author: Catherine Tong, Tom Joy


##Introduction

This notebook covers essential Python concepts that we will use frequently during the GirlsWhoML courses.

Please feel free to use this notebook as a reference if you get stuck in the future. If you get stuck during the notebook or have a question, please ask your demonstrator for help, they're there to help you.

We've kept this very streamlined with the hope that you'll talk to each other about how implementing the tasks. This is designed to be very collaborative and just as much of a networking event as it is eductional. So please help each other out and use the internet if you need to!

# Variables

Create three variables called: x, y, z, which hold the data 3, '3', and 'three'. Think carefully about why types these variables will be.

In [50]:
x = 3          
y = 3            
z = 'three'           
print(x, y, z)

print(f"the value of x is {x:.3f}")

3 3 three
the value of x is 3.000


# Types

Print out the types of the variables x, y, z. You can do this useing the `type(variable_name)` function.

In [3]:
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'str'>


# Operators

Print out the values of: x * x, x^2, x + 3, x - 2, x / 2, x % 2.

Talk to your demonstrator about what would happend if you tried to compute x * y.

In [6]:
print(x*x)
print(x^2)
print(x + 3)
print(x - 2)
print(x/2)
print(x % 2)

9
1
6
1
1.5
1


# Logic

This simple tasks asks you to write a short program which will describe the weather based on some observations. You will be given two boolean variables (true or false), which tell you if it's raining or not (`raining`)and if it's sunny or not (`sunny`). Given these inputs, implement some logic which will print:

* 'It's raining and cloudy', if `raining = True` and `sunny = False`
* 'It's dry but cloudy', if `raining = False` and `sunny = False`
* "It's dry and sunny!", if `raining = False` and `sunny = Sunny`
* "There's a rainbow!", if `raining = True` and `sunny = True`

You will need to use a combination `if else` statements. This is quite a hard task, so it might be worth discussing with each other and your demonstrator before launching in.

HINT: You can either use the `and` operator in the statement, or you can also use multiple levels of `if else` statements.





In [51]:
raining = True
sunny = True

if raining == True & sunny == False:
    print("It's raining and cloudy")
elif raining == False & sunny == False:
    print("It's dry but cloudy")
elif raining == False & sunny == Sunny:
    print("It's dry and sunny!")
elif raining == True & sunny == True:
    print("There's a rainbow!")


There's a rainbow!


# Data Structures

This is a key part of Python, you'll use the concepts almost everytime you do some programming, so it's important to take your time making sure you understand what's going on and how to use them.

## Tuples

Create a tuple containing the digits `1, 3, 5`

In [11]:
my_tuple = (1, 3, 5)

What happens if you want to change the second element to contain the value 4, can you do it?

No, items cannot be changed in tuples

## Lists

Create a list containing the digits `1, 3, 5, 7, 8`


In [12]:
my_list = [1, 3, 5, 7, 8]

## Dictionaries

Create a list containing the values `1, 3, 5`. Use suitable names for the keys.

In [17]:
my_dictionary = {'first': 1,
                'second': 3,
                'third': 5} # TODO

# Loops

Write a loop to calculate the sum of `my_tuple`.

In [15]:
sum = 0
for item in my_tuple:
    sum += item
print(sum)

9


Write a loop to calculate the sum of my_list.



In [16]:
sum = 0
for item in my_list:
    sum += item
    
print(sum)

24


Write a loop which will calculate the sum of all the elements in `my_dictionary`.

HINT: You may need to ask your demonstrator or use Google to help you out.

In [20]:
sum = 0
for key in my_dictionary:
    sum += my_dictionary[key]
    
print(sum)

9


# Functions

In the previous excersie we had to wite the same piece of code twice to sum up the tuple and the list. We can clean this up a little bit by putting this functionality into a function. This saves us having the same bits of code written twice, which is always a bad idea.

In [52]:
def sum_array(array):
  # TODO add functinality here which will sum up all elements in array
    sum = 0
    for item in array:
        sum += item
    return sum

print(sum_array(my_tuple))
print(sum_array(my_list))

9
24


# Classes

Classes can be a bit of a scary concept at first, but are an essential part of programming. The easiest way to think about classes is to think of them as components/modules in a machine, which perorm self contained tasks, but can also interact with other classes. This provides a way for us abstract how things are implemented in the codebase and makes life alot easier when it gets quite large. We'll keep things very simple to start with, as this concept can take a while to grasp, so don't worry if you don't get it right away. Chat with your demonstator and others in the breakout room about classes, discussing is always helpful.

As a simple example we're going to use animals. We'll also explore a concept called inheritence, which is a way to enforce that classes are of the same base type, but different, e.g. a bear and a dog are both mammals but not quite the same. 

In [23]:
class Mammal():
  def __init__(self, name):
    self.name = name # to be able to access name in other functions

  def speak(self):
    print("Hi there my name is %s" % self.name)


class Bear(Mammal):
  def __init__(self, name):
    super().__init__(name) # this instantiates the base class Mammal

  def dance(self):
    # in here we can make the bear dance
    print("Everybody dance, clap your hands, clap your hands...") # Chic fan here


class Dog(Mammal):
  def __init__(self, name):
    super().__init__(name)

  def fetch(self):
    # in here we can make the dog fetch
    print("Fetch the ball!")


Have a look at the code above closely and talk it through it with your demonstrator. It's important you understand what every piece of the code is doing, don't be affraid to ask if you don't understand what a bit of code is doing.


Question: What happens if we now wanted to add a class about reptiles? How would you incorporate this class into the above example? Think carefull about what a base class might be and what you'd need to change. 

In [24]:
class Reptile(): # TODO what base class should Reptile inherit from?
  def __init__(self, name):
    # TODO will we need to call super().__init__()?
    self.name = name
  def sunbathe(self):
    print("Vitamin-D + SPF + G&T, doesn't get better than this.")

# Libraries

When programming in Python, there's tasks which come up very often, so often in fact that people all over the world have devoted time to write functions and classes which fulfil these common tasks, meaning you don't have to write basic functions from scratch every time. These tasks cover all sorts, e.g. plotting graphs, using matrices etc and are contained in 'modules'.

One module which you'll use very very often is numpy. You can import numpy into your programm using: 

```
import numpy as np
```

You can then access all of numpy's functinality through `np.<nfunction>`, you can check out all of the functions and features here: https://numpy.org/.

One of the main featues of numpy is the `np.array` class. It's a way to taks normal Python lists, but add lots of functinality such as mupltiplication etc. You can make a numpy array using `np.array(my_data)`. Create a numpy array called `my_array` below.

In [39]:
import numpy as np
data = [1, 2, 3, 4, 5]
my_array = np.array(data)

You can sum up numpy arrays using `.sum()`. Try this below and check the answer is as expected.

In [29]:
my_array.sum()

15

Have a look on the numpy website to see if you can find ways to: multiply my_array by a constant; add a constant and add two arrays together. This excersie is designed to get you comfortable with using the internet to find your answers. 90% of programming is looking up on Google how to do little tasks, as a programmer your job is to bring it all together and know where to look to find the right answer. Don't waste your precious brain power memorizing things, just know where to look to find the right answer.

In [32]:
print(np.multiply(my_array, 3))
print(np.add(my_array, 3))
print(np.add(my_array, my_array))

[ 3  6  9 12 15]
[4 5 6 7 8]
[ 2  4  6  8 10]


### 2D Arrays

Often we want more dimensions in an array than a 1D array, i.e. a matrix, or a grid of numbers. We can easily extend lists and arrays to hold 2D arrays.

```
my_2d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
```

Create a numpy array using the data in `my_2d_list`.


In [34]:
my_2d_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

my_2d_array = np.array(my_2d_list)
print(my_2d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Slices

We can access elements or slices of arrays using the square brackes `[]`.

Using `my_array` which you created previously, print out the 2nd element, and then create a an array which removes the first and last elements of `my_array`.

Hint: You can access elements from the right side by using a minus index, e.g. the last element can be accessing by `my_array[-1]`.



In [40]:
print(my_array[1])

my_array = np.delete(my_array, 0)
my_array = np.delete(my_array, -1)
print(my_array)

2
[2 3 4]


## Slicing in 2D arrays

We can access elements of 2d Arrays using `[x, y]` at the end of a 2d array, e.g. `my_2d_array[1, 1]` will print the value 5.

The first element accesses the rows and the second the columns, to use the entire rows or columns we use colon `:`, e.g. `my_2d_array[:, :] == my_2d_array'.

Because we may have more than two dimensions, we use axis rather than rows and columns. An easy way to think about this is arrays of arrays, e.g. the elements of axis 0 contain arrays. It's worth taking a moment to think about this, but if you get stuck just think about the image below.

<div>
<img src="https://i.stack.imgur.com/h1alT.jpg" width="500"/>
</div>


Using the `:` operator, try and print the first row and then the first column of `my_2d_array`.

In [45]:
print(my_2d_array)
print(my_2d_array[0, :])
print(my_2d_array[:, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3]
[1 4 7]


In [46]:
import numpy as np

class Car():
  def __init__(self, model, color):
    self.model = model
    self.color = color
    self.dt = 1.0 # 1 second
    self.position = np.array([0, 0]) # initial position

  def move(self, velocity):
    self.position = self.position + self.dt * velocity

In [47]:
my_car = Car(model="Tesla", color="Red")

print("Position at t = 0:", my_car.position)

velocity = np.array([1, 1])
my_car.move(velocity)

print("Position at t = 1:", my_car.position)


Position at t = 0: [0 0]
Position at t = 1: [1. 1.]


In [ ]:
€